
version: '3.8'

services:
  service1:
    build: ./service1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/service1"]
      interval: 10s
      retries: 3
    networks:
      - appnet

  service2:
    build: ./service2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/service2"]
      interval: 10s
      retries: 3
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service1
      - service2
    networks:
      - appnet

networks:
  appnet:
    driver: bridge





